--first push
Sanjuchilukuri/Tezo_Employee pull request #1
Opened 2024-02-01 08:08 UTC by Sanjuchilukuri

2024-02-01 09:24 UTC, karthik2265 commented
Hii

2024-02-01 09:26 UTC, karthik2265 requested changes

2024-02-01 09:26 UTC, karthik2265 commented on css/index.css
> +body {
I've noticed a set of styles that are duplicated in both empInf.css and roles.css. To enhance code organization and encourage reusability across all pages, I suggest consolidating these shared styles into a separate CSS file.

2024-02-01 09:26 UTC, karthik2265 commented on html/roles.html
> +                  <div class="employees">
avoid writing class names matching the content
This video explains how to write semantic css take a look: https://www.youtube.com/watch?v=lWu5zf_S9R4

2024-02-01 09:26 UTC, karthik2265 commented on html/roles.html
> +              <div class="roles-wrapper">
if you notice each item in the sidebar has some common styles like padding, gap between text and icon ..etc you can have a class like sidebar-item which has these common styles and use it.

2024-02-01 09:26 UTC, karthik2265 commented on css/empInf.css
> +          padding: 15px 24px;
we should prefer to use rems wherever possible

2024-02-05 09:25 UTC, Sanjuchilukuri commented
I've resolved those changes. Could you please check them? Commit ID: 309a6a9.

2024-02-05 10:28 UTC, merged